### ISSUE TITLE
New Poseidon Hash/MHT

### ISSUE THREAD

**Issue by albertog78** [HorizenOfficial/zendoo-mc-cryptolib#17]
To be able to not have to collect first all the inputs together and then passing them to poseidon, expose via JNI the new implementation coming from ginger lib (ZencashOfficial/ginger-lib#56)

**Comment by DanieleDiBenedetto** [comment]
Also implement in-memory random access merkle tree based on this hash

**Comment by DanieleDiBenedetto** [comment]
Done in #27
